CREATE TABLE [ukrtax].[DELETEDRECORDSLOG]
(
	[DataSetRow] INT REFERENCES store.DataSetRow(Id) NOT NULL,
    [IDMNGUNIT]   INT          NOT NULL,
    [FMGUID]      UNIQUEIDENTIFIER    NOT NULL,
    [LAYERNAME]   VARCHAR (80) NOT NULL,
    [TIMESTAMP]   DATETIME     NOT NULL,
    [DELETE_DATE] DATETIME     NOT NULL,
    [DELETE_USER] VARCHAR (8)  NULL,
    [PLOTSGUID]   UNIQUEIDENTIFIER    NOT NULL,
	[_Status] TINYINT NOT NULL REFERENCES mca.status(Id) DEFAULT 1,
	[CHANGE_SESSION] [int] NOT NULL REFERENCES mca.session(ID) DEFAULT mca.DefaultSession(),
	[SysStart] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEnd] DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL, 
    CONSTRAINT [PK_DELETEDRECORDSLOG] PRIMARY KEY ([DataSetRow]),
	PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd])
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=[ukrtax].[DELETEDRECORDSLOG_HISTORY], DATA_CONSISTENCY_CHECK=ON))
GO

CREATE UNIQUE INDEX [IX_DELETEDRECORDSLOG_Keys] ON [ukrtax].[DELETEDRECORDSLOG] ([IDMNGUNIT], [FMGUID])
GO
