CREATE TABLE [ukrtax].[GEOMETRY_COLUMNS]
(
	[DataSetRow] INT REFERENCES store.DataSetRow(Id) NOT NULL,
    [F_TABLE_NAME]      VARCHAR (256) NOT NULL,
    [F_GEOMETRY_COLUMN] VARCHAR (256) NOT NULL,
    [GEOMETRY_TYPE]     VARCHAR (30)  NOT NULL,
	[_Status] TINYINT NOT NULL REFERENCES mca.status(Id) DEFAULT 1,
	[CHANGE_SESSION] [int] NOT NULL REFERENCES mca.session(ID) DEFAULT mca.DefaultSession(),
	[SysStart] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEnd] DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL,
    CONSTRAINT [PK_GEOMETRY_COLUMNS] PRIMARY KEY ([DataSetRow]), 
	PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd])
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=[ukrtax].[GEOMETRY_COLUMNS_HISTORY], DATA_CONSISTENCY_CHECK=ON))
GO

CREATE UNIQUE INDEX [IX_GEOMETRY_COLUMNS_Keys] ON [ukrtax].[GEOMETRY_COLUMNS] ([F_TABLE_NAME], [F_GEOMETRY_COLUMN], [GEOMETRY_TYPE])
GO