CREATE TABLE [ukrtax].[SYNCHROLOG]
(
	[DataSetRow] INT REFERENCES store.DataSetRow(Id) NOT NULL,
    [SESSIONSTART] DATETIME        NOT NULL,
    [SESSIONEND]   DATETIME        NOT NULL,
    [ADD_USER]     VARCHAR (8)     NOT NULL,
    [SESSIONGUID]  CHAR (38)       NOT NULL,
    [IPADDRESS]    VARCHAR (40)    NULL,
    [DESCRIPTION]  NTEXT           NULL,
    [DATA]         VARBINARY (MAX) NULL,
    [LOCKCODE]     VARCHAR (30)    NULL,
	[_Status] TINYINT NOT NULL REFERENCES mca.status(Id) DEFAULT 1,
	[CHANGE_SESSION] [int] NOT NULL REFERENCES mca.session(ID) DEFAULT mca.DefaultSession(),
	[SysStart] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEnd] DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL,
    PRIMARY KEY ([DataSetRow]), 
	PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd])
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=[ukrtax].[SYNCHROLOG_HISTORY], DATA_CONSISTENCY_CHECK=ON))
GO

CREATE UNIQUE INDEX [IX_SYNCHROLOG_Keys] ON [ukrtax].[SYNCHROLOG] ([SESSIONSTART])
GO
