CREATE TABLE [ukrtax].[SYSTEMFILES]
(
	[DataSetRow] INT REFERENCES store.DataSetRow(Id) NOT NULL,
    [FILENAME]   VARCHAR (36)    NOT NULL,
    [ADD_DATE]   DATETIME        NOT NULL,
    [ADD_USER]   VARCHAR (8)     NOT NULL,
    [FMGUID]     VARCHAR (38)    NOT NULL,
    [PARAMETERS] VARCHAR (80)    NULL,
    [DATA]       VARBINARY (MAX) NULL,
	[_Status] TINYINT NOT NULL REFERENCES mca.status(Id) DEFAULT 1,
	[CHANGE_SESSION] [int] NOT NULL REFERENCES mca.session(ID) DEFAULT mca.DefaultSession(),
	[SysStart] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEnd] DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL,
    PRIMARY KEY ([DataSetRow]), 
	PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd])
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=[ukrtax].[SYSTEMFILES_HISTORY], DATA_CONSISTENCY_CHECK=ON))
GO

CREATE UNIQUE INDEX [IX_SYSTEMFILES_Keys] ON [ukrtax].[SYSTEMFILES] ([FILENAME])
GO