CREATE TABLE [store].[DataSetRow]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[DataSet] INT NOT NULL REFERENCES ds.dataset(Id),
	[_Status] TINYINT NOT NULL REFERENCES mca.status(Id) DEFAULT 1,
	[CHANGE_SESSION] [int] NOT NULL REFERENCES mca.session(ID) DEFAULT mca.DefaultSession(),
	[SysStart] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEnd] DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd])
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=[store].[DataSetRow_HISTORY], DATA_CONSISTENCY_CHECK=ON))
