CREATE TABLE [store].[DataSetValueNVARCHAR_SHORT]
(
	[DataSetValue] BIGINT NOT NULL REFERENCES store.DataSetValue(Id),
	[Value] NVARCHAR(32) NOT NULL,
	[_Status] TINYINT NOT NULL REFERENCES mca.status(Id) DEFAULT 1,
	[CHANGE_SESSION] [int] NOT NULL REFERENCES mca.session(ID) DEFAULT mca.DefaultSession(),
	[SysStart] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEnd] DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL,
    CONSTRAINT [PK_DataSetValueNVARCHAR_SHORT] PRIMARY KEY ([DataSetValue]),
	PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd])
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=[store].[DataSetValueNVARCHAR_SHORT_HISTORY], DATA_CONSISTENCY_CHECK=ON))
