CREATE TABLE [store].[DataSetValue]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[DataSetRow] INT NOT NULL REFERENCES store.DataSetRow(Id),
    [Element]  INT NOT NULL REFERENCES ds.element(Id),
	[_Status] TINYINT NOT NULL REFERENCES mca.status(Id) DEFAULT 1,
	[CHANGE_SESSION] [int] NOT NULL REFERENCES mca.session(ID) DEFAULT mca.DefaultSession(),
	[SysStart] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEnd] DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd])
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=[store].[DataSetValue_HISTORY], DATA_CONSISTENCY_CHECK=ON))
