CREATE TABLE [mca].[status]
(
	[Id] TINYINT NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(16),
	[SysStart] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEnd] DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd])
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=[mca].[status_HISTORY], DATA_CONSISTENCY_CHECK=ON))
